export const apiRoutes = {
  deputados: '/deputados',
  deputadoById: (id: number) => `/deputados/${id}`,
  despesasDeputado: (id: number) => `/deputados/${id}/despesas`,
  discursosDeputado: (id: number) => `/deputados/${id}/discursos`,
  eventosDeputado: (id: number) => `/deputados/${id}/eventos`,
  frentesDeputado: (id: number) => `/deputados/${id}/frentes`,
  historicoDeputado: (id: number) => `/deputados/${id}/historico`,
  mandatosDeputado: (id: number) => `/deputados/${id}/mandatos`,
  ocupacoesDeputado: (id: number) => `/deputados/${id}/ocupacoes`,
  orgaosDeputado: (id: number) => `/deputados/${id}/orgaos`,
  profissoesDeputado: (id: number) => `/deputados/${id}/profissoes`,

  proposicoes: '/proposicoes',
  proposicaoById: (id: number) => `/proposicoes/${id}`,
  autoresProposicao: (id: number) => `/proposicoes/${id}/autores`,
  relatedProposicao: (id: number) => `/proposicoes/${id}/relacionadas`,
  temasProposicao: (id: number) => `/proposicoes/${id}/temas`,
  tramitacoesProposicao: (id: number) => `/proposicoes/${id}/tramitacoes`,
  votacoesProposicao: (id: number) => `/proposicoes/${id}/votacoes`,

  partidos: '/partidos',
  partidoById: (id: number) => `/partidos/${id}`,
  frentesParlamentares: '/frentes',
  frenteParlamentarById: (id: number) => `/frentes/${id}`,

  eventos: '/eventos',
  eventoById: (id: number) => `/eventos/${id}`,
  votacoesEvento: (id: number) => `/eventos/${id}/votacoes`,
  deputadosEvento: (id: number) => `/eventos/${id}/deputados`,

  blocosPartidarios: '/blocos',
  votacoes: '/votacoes',
  votacaoById: (id: number) => `/votacoes/${id}`,

  orgaos: '/orgaos',
  orgaoById: (id: string) => `/orgaos/${id}`,
  votacoesOrgao: (id: string) => `/orgaos/${id}/votacoes`,
  membrosOrgao: (id: string) => `/orgaos/${id}/membros`,
  eventosOrgao: (id: string) => `/orgaos/${id}/eventos`,
}
