export const apiRoutes = {
  deputados: '/deputados',
  deputadoById: (id: number) => `/deputados/${id}`,
  despesasDeputado: (id: number) => `/deputados/${id}/despesas`,
  discursosDeputado: (id: number) => `/deputados/${id}/discursos`,
  eventosDeputado: (id: number) => `/deputados/${id}/eventos`,
  frentesDeputado: (id: number) => `/deputados/${id}/frentes`,
  historicoDeputado: (id: number) => `/deputados/${id}/historico`,
  mandatosDeputado: (id: number) => `/deputados/${id}/mandatos`,
  ocupacoesDeputado: (id: number) => `/deputados/${id}/ocupacoes`,
  orgaosDeputado: (id: number) => `/deputados/${id}/orgaos`,
  profissoesDeputado: (id: number) => `/deputados/${id}/profissoes`,
  partidos: '/partidos',
  partidoById: (id: number) => `/partidos/${id}`,
  frentesParlamentares: '/frentes',
  frenteParlamentarById: (id: number) => `/frentes/${id}`,
  proposicoes: '/proposicoes',
  proposicaoById: (id: number) => `/proposicoes/${id}`,
  eventos: '/eventos',
  eventoById: (id: number) => `/eventos/${id}`,
  blocosPartidarios: '/blocos',
  votacoes: '/votacoes',
  votacaoById: (id: number) => `/votacoes/${id}`,
  orgaos: '/orgaos',
  orgaoById: (id: number) => `/orgaos/${id}`,
}
