export const TIPOS_PROPOSICAO = [
  {
    cod: '129',
    sigla: 'CON',
    nome: 'Consulta',
    descricao: 'Consulta',
  },
  {
    cod: '130',
    sigla: 'EMC',
    nome: 'Emenda na Comissão',
    descricao: 'Emenda Apresentada na Comissão',
  },
  {
    cod: '131',
    sigla: 'EMP',
    nome: 'Emenda de Plenário',
    descricao: 'Emenda de Plenário',
  },
  {
    cod: '132',
    sigla: 'EMS',
    nome: 'Emenda/Substitutivo do Senado',
    descricao: 'Emenda/Substitutivo do Senado',
  },
  {
    cod: '133',
    sigla: 'INC',
    nome: 'Indicação ',
    descricao: 'Indicação',
  },
  {
    cod: '134',
    sigla: 'MSC',
    nome: 'Mensagem',
    descricao: 'Mensagem',
  },
  {
    cod: '135',
    sigla: 'PDC',
    nome: 'Projeto de Decreto Legislativo',
    descricao: 'Projeto de Decreto Legislativo',
  },
  {
    cod: '136',
    sigla: 'PEC',
    nome: 'Proposta de Emenda à Constituição',
    descricao:
      'Proposta de Emenda à Constituição (Art. 60 CF c/c art. 201 a 203, RICD)',
  },
  {
    cod: '137',
    sigla: 'PET',
    nome: 'Petição',
    descricao: 'Petição',
  },
  {
    cod: '138',
    sigla: 'PFC',
    nome: 'Proposta de Fiscalização e Controle',
    descricao: 'Proposta de Fiscalização e Controle',
  },
  {
    cod: '139',
    sigla: 'PL',
    nome: 'Projeto de Lei',
    descricao: 'Projeto de Lei',
  },
  {
    cod: '140',
    sigla: 'PLP',
    nome: 'Projeto de Lei Complementar',
    descricao: 'Projeto de Lei Complementar (Art. 61 CF)',
  },
  {
    cod: '141',
    sigla: 'PRC',
    nome: 'Projeto de Resolução',
    descricao: 'Projeto de Resolução',
  },
  {
    cod: '142',
    sigla: 'PRN',
    nome: 'Projeto de Resolução do Congresso Nacional',
    descricao: 'Projeto de Resolução (CN)',
  },
  {
    cod: '143',
    sigla: 'RCP',
    nome: 'Requerimento de Instituição de CPI',
    descricao:
      'Requerimento de Instituição de Comissão Parlamentar de Inquérito',
  },
  {
    cod: '144',
    sigla: 'REC',
    nome: 'Recurso',
    descricao: 'Recurso',
  },
  {
    cod: '145',
    sigla: 'REM',
    nome: 'Reclamação',
    descricao: 'Reclamação',
  },
  {
    cod: '146',
    sigla: 'REP',
    nome: 'Representação',
    descricao: 'Representação',
  },
  {
    cod: '147',
    sigla: 'REQ',
    nome: 'Requerimento',
  },
  {
    cod: '148',
    sigla: 'RIC',
    nome: 'Requerimento de Informação',
    descricao: 'Requerimento de Informação (Art. 116, RICD)',
  },
  {
    cod: '150',
    sigla: 'REQ',
    nome: 'Requerimento de Convocação de Autoridade',
  },
  {
    cod: '151',
    sigla: 'SIT',
    nome: 'Solicitação de Informação ao TCU',
    descricao: 'Solicitação de Informação ao TCU',
  },
  {
    cod: '153',
    sigla: 'TVR',
    nome: 'Ato de Concessão e Renovação de Concessão de Emissora de Rádio e Televisão',
    descricao: 'TVR',
  },
  {
    cod: '154',
    sigla: 'REC',
    nome: 'Recurso do Congresso Nacional',
    descricao: 'Recurso do Congresso Nacional',
  },
  {
    cod: '171',
    sigla: 'INA',
    nome: 'Indicação de Autoridade',
    descricao: 'Indicação de Autoridade',
  },
  {
    cod: '181',
    sigla: 'OF',
    nome: 'Ofício',
    descricao: 'Ofício',
  },
  {
    cod: '185',
    sigla: 'P.C',
    nome: 'Parecer (CD)',
    descricao: 'Parecer (CD)',
  },
  {
    cod: '187',
    sigla: 'PAR',
    nome: 'Parecer de Comissão',
    descricao: 'Parecer de Comissão',
  },
  {
    cod: '189',
    sigla: 'MAN',
    nome: 'Manifestação do Relator',
    descricao: 'Manifestação do Relator',
  },
  {
    cod: '190',
    sigla: 'PRL',
    nome: 'Parecer do Relator',
    descricao: 'Parecer Relator',
  },
  {
    cod: '191',
    sigla: 'PRV',
    nome: 'Parecer Vencedor',
    descricao: 'Parecer Vencedor',
  },
  {
    cod: '192',
    sigla: 'PPP',
    nome: 'Parecer Proferido em Plenário',
    descricao: 'Parecer Proferido em Plenário',
  },
  {
    cod: '193',
    sigla: 'PRR',
    nome: 'Parecer Reformulado',
    descricao: 'Parecer Reformulado',
  },
  {
    cod: '195',
    sigla: 'CVO',
    nome: 'Complementação de Voto',
    descricao: 'Complementação de Voto',
  },
  {
    cod: '196',
    sigla: 'PES',
    nome: 'Parecer às Emendas Apresentadas ao Substitutivo do Relator',
    descricao: 'Parecer às emendas apresentadas ao Substitutivo do Relator ',
  },
  {
    cod: '197',
    sigla: 'RDF',
    nome: 'Redação Final',
    descricao: 'Redação Final',
  },
  {
    cod: '201',
    sigla: 'MAN',
    nome: 'Manifestação pela Prejudicialidade da Matéria',
    descricao: 'Manifestação pela Prejudicialidade da Matéria',
  },
  {
    cod: '202',
    sigla: 'MAN',
    nome: 'Manifestação pela Incompetência da Comissão',
    descricao: 'Manifestação pela Incompetência da Comissão',
  },
  {
    cod: '211',
    sigla: 'PRF',
    nome: 'Projeto de Resolução do Senado Federal',
    descricao: 'Projeto de Resolução do Senado Federal',
  },
  {
    cod: '246',
    sigla: 'CST',
    nome: 'Solicitação de Pronunciamento',
    descricao: 'CST',
  },
  {
    cod: '253',
    sigla: 'SGM',
    nome: 'Ofício da Mesa',
    descricao: 'Ofício da Mesa',
  },
  {
    cod: '254',
    sigla: 'DIS',
    nome: 'Discurso',
    descricao: 'Discurso',
  },
  {
    cod: '255',
    sigla: 'SBT',
    nome: 'Substitutivo',
    descricao: 'Substitutivo',
  },
  {
    cod: '256',
    sigla: 'SBE',
    nome: 'Subemenda',
    descricao: 'Subemenda',
  },
  {
    cod: '257',
    sigla: 'EMR',
    nome: 'Emenda de Relator',
    descricao: 'Emenda de Relator',
  },
  {
    cod: '258',
    sigla: 'ESB',
    nome: 'Emenda ao Substitutivo',
    descricao: 'Emenda ao Substitutivo',
  },
  {
    cod: '260',
    sigla: 'VTS',
    nome: 'Voto em Separado',
    descricao: 'Voto em Separado',
  },
  {
    cod: '261',
    sigla: 'DTQ',
    nome: 'Destaque',
    descricao: 'Destaque',
  },
  {
    cod: '262',
    sigla: 'REL',
    nome: 'Relatório de Subcomissão',
    descricao: 'Relatório de Subcomissão',
  },
  {
    cod: '263',
    sigla: 'DTN',
    nome: 'Destaque (CN)',
    descricao: 'Destaque de Bancada (CN) ou Destaque Simples (CN)',
  },
  {
    cod: '270',
    sigla: 'DVT',
    nome: 'Declaração de Voto',
    descricao: 'Declaração de Voto',
  },
  {
    cod: '273',
    sigla: 'EML',
    nome: 'Emenda à LDO',
    descricao: 'Emenda à LDO',
  },
  {
    cod: '276',
    sigla: 'SDL',
    nome: 'Sugestão de Emenda à LDO - CLP',
    descricao: 'Sugestão de Emenda à LDO',
  },
  {
    cod: '285',
    sigla: 'SUG',
    nome: 'Sugestão',
    descricao: 'Sugestão',
  },
  {
    cod: '286',
    sigla: 'SUM',
    nome: 'Súmula',
    descricao: 'Súmula',
  },
  {
    cod: '287',
    sigla: 'EMO',
    nome: 'Emenda ao Orçamento',
    descricao: 'Emenda ao Orçamento',
  },
  {
    cod: '288',
    sigla: 'SOA',
    nome: 'Sugestão de Emenda ao Orçamento - CLP',
    descricao: 'Sugestão de Emenda ao Orçamento',
  },
  {
    cod: '289',
    sigla: 'REL',
    nome: 'Relatório de CPI',
    descricao: 'Relatório de CPI',
  },
  {
    cod: '290',
    sigla: 'EMD',
    nome: 'Emenda',
    descricao: 'Emenda',
  },
  {
    cod: '291',
    sigla: 'MPV',
    nome: 'Medida Provisória',
    descricao: 'Medida Provisória',
  },
  {
    cod: '292',
    sigla: 'REL',
    nome: 'Relatório',
    descricao: 'Relatório',
  },
  {
    cod: '293',
    sigla: 'REQ',
    nome: 'Requerimento de Sessão Solene',
  },
  {
    cod: '294',
    sigla: 'REQ',
    nome: 'Requerimento de Audiência Pública',
  },
  {
    cod: '295',
    sigla: 'DEN',
    nome: 'Denúncia',
    descricao: 'Denúncia',
  },
  {
    cod: '296',
    sigla: '',
    nome: 'D) PARECERES, MANIFESTAÇÕES E REDAÇÃO FINAL',
    descricao: 'E) PARECERES, MANIFESTAÇÕES E REDAÇÃO FINAL',
  },
  {
    cod: '297',
    sigla: '',
    nome: 'C) EMENDAS (RICD Cap. V)',
    descricao: 'D) EMENDAS (RICD Cap. V)',
  },
  {
    cod: '298',
    sigla: '',
    nome: 'H) OUTRAS PROPOSIÇÕES ACESSÓRIAS',
    descricao: 'OUTRAS PROPOSIÇÕES ACESSÓRIAS',
  },
  {
    cod: '299',
    sigla: '',
    nome: 'E) REQUERIMENTOS (RICD Cap IV)',
    descricao: 'F) REQUERIMENTOS (RICD Cap IV)',
  },
  {
    cod: '301',
    sigla: '',
    nome: 'A) PROPOSIÇÕES CF/88 Art. 59',
    descricao: 'A) PROPOSIÇÕES CF/88 Art. 59',
  },
  {
    cod: '302',
    sigla: '',
    nome: 'B) PROPOSIÇÕES CF/88 Arts 58, 70 e 223, e RICD Art 100.',
    descricao: 'B) PROPOSIÇÕES CF/88 Arts 58, 70 e 233, e RICD Art 100.',
  },
  {
    cod: '303',
    sigla: '',
    nome: 'F) SUGESTÕES',
    descricao: 'G) SUGESTÕES',
  },
  {
    cod: '304',
    sigla: 'REQ',
    nome: 'Requerimento de Apensação',
    descricao: 'Ar. 142, RICD',
  },
  {
    cod: '305',
    sigla: 'REQ',
    nome: 'Requerimento de Desapensação',
  },
  {
    cod: '306',
    sigla: 'REQ',
    nome: 'Requerimento de Audiência solicitada por Deputado',
  },
  {
    cod: '307',
    sigla: 'REQ',
    nome: 'Requerimento de Audiência solicitada por Comissão ou Deputado',
  },
  {
    cod: '308',
    sigla: 'REQ',
    nome: 'Requerimento de Redistribuição',
  },
  {
    cod: '310',
    sigla: 'REQ',
    nome: 'Requerimento de Inclusão ou Retirada de Assinatura em Proposição de Iniciativa Coletiva Obrigatória',
  },
  {
    cod: '311',
    sigla: 'REQ',
    nome: 'Requerimento de Retirada de Proposição de Iniciativa Individual',
  },
  {
    cod: '312',
    sigla: 'REQ',
    nome: 'Requerimento de Retirada de Proposição de Iniciativa Coletiva',
  },
  {
    cod: '313',
    sigla: 'REQ',
    nome: 'Requerimento de Inclusão ou Retirada de Assinatura em Proposição de Iniciativa Individual',
  },
  {
    cod: '314',
    sigla: 'REQ',
    nome: 'Requerimento de Envio de proposições pendentes de parecer à Comissão seguinte ou ao Plenário',
  },
  {
    cod: '315',
    sigla: 'REQ',
    nome: 'Requerimento de Retirada do requerimento de urgência (matéria com requerimento apresentado e não votado)',
  },
  {
    cod: '316',
    sigla: 'REQ',
    nome: 'Requerimento de Retirada do requerimento de informação',
  },
  {
    cod: '317',
    sigla: 'REQ',
    nome: 'Requerimento de Constituição de Comissão Parlamentar de Inquerito (CPI)',
  },
  {
    cod: '318',
    sigla: 'REQ',
    nome: 'Requerimento de Inclusão de Matéria na Ordem do Dia',
    descricao: 'Inclusão na Ordem do Dia (Art. 135 c/c 114, XIV, RICD)',
  },
  {
    cod: '319',
    sigla: 'REQ',
    nome: 'Requerimento de Retirada de Proposição',
    descricao:
      'Retirada de proposição com parecer (Art. 104, c/c art. 114, V e VII, RICD)',
  },
  {
    cod: '321',
    sigla: 'REQ',
    nome: 'Requerimento de Extinção do regime de urgência (matéria com urgência votada)',
    descricao: 'Extinção do regime de urgência (Art. 156, c/c art. 104, RICD)',
  },
  {
    cod: '322',
    sigla: 'REQ',
    nome: 'Requerimento de Tramitação de proposição em regime de prioridade',
  },
  {
    cod: '323',
    sigla: 'REQ',
    nome: 'Requerimento de Quebra de Interstício para Inclusão de Matéria na Ordem do Dia',
    descricao:
      'Dispensa de interstício para inclusão na Ordem do Dia (Art. 150, § único, RICD)',
  },
  {
    cod: '324',
    sigla: 'REQ',
    nome: 'Requerimento de Destaque para votação em separado de parte de proposição (DVS)',
  },
  {
    cod: '327',
    sigla: 'RPD',
    nome: 'Requerimento de Retirada da OD de proposições com pareceres favoraveis',
  },
  {
    cod: '328',
    sigla: 'RPD',
    nome: 'Requerimento de Retirada de Pauta',
    descricao:
      'Retirada da OD de proposição nela incluída (Art. 117, VI, RICD)',
  },
  {
    cod: '329',
    sigla: 'RPD',
    nome: 'Requerimento de Adiamento da Discussão',
    descricao:
      'Adiamento de discussão nos termos do art. 177, c/c art. 101, II,2, RICD.',
  },
  {
    cod: '330',
    sigla: 'RPD',
    nome: 'Requerimento de Dispensa da Discussão',
    descricao: 'Dispensa da discussão (Art. 101, II, 2, RICD)',
  },
  {
    cod: '331',
    sigla: 'RPD',
    nome: 'Requerimento de Encerramento da Discussão',
    descricao:
      'Encerramento de discussão (Art. 178, § 2º, c/c art. 101, II, 2, RICD)',
  },
  {
    cod: '332',
    sigla: 'RPD',
    nome: 'Requerimento de Votação pelo Processo Nominal',
    descricao:
      'Votação por determinado processo (Art. 101, II, 3, c/c art. 189, § 3º, RICD)',
  },
  {
    cod: '333',
    sigla: 'RPD',
    nome: 'Requerimento de Votação parcelada da proposição',
    descricao:
      'Votação em globo ou parcelada (Art. 101, II, 3, c/c art. 189, § 3º RICD)',
  },
  {
    cod: '334',
    sigla: 'RPD',
    nome: 'Requerimento de Verificação de Votação',
    descricao: 'Verificação de votação (Art. art. 185, §5º, RICD)',
  },
  {
    cod: '335',
    sigla: 'RPD',
    nome: 'Requerimento de Votação por escrutínio secreto',
    descricao: 'Votação por escrutínio secreto (Art. 188, II, RICD)',
  },
  {
    cod: '336',
    sigla: 'RPD',
    nome: 'Requerimento de Adiamento da Votação',
    descricao:
      'Adiamento da votação nos termos do Art. 193º c/c 117, X do RICD.',
  },
  {
    cod: '337',
    sigla: 'RPD',
    nome: 'Requerimento de Preferência',
    descricao:
      'Preferência para votação ou discussão de uma proposição (Art. 160, RICD)',
  },
  {
    cod: '338',
    sigla: 'RPD',
    nome: 'Requerimento de Dispensa do Avulso da Redação Final',
  },
  {
    cod: '339',
    sigla: 'REQ',
    nome: 'Requerimento de Reconstituição de proposição',
  },
  {
    cod: '340',
    sigla: 'REQ',
    nome: 'Requerimento de Inclusão na Ordem do Dia de proposição (Durante o período ordinário)',
  },
  {
    cod: '341',
    sigla: 'REQ',
    nome: 'Requerimento de Publicação de Parecer de Comissão aprovado',
  },
  {
    cod: '342',
    sigla: 'REQ',
    nome: 'Requerimento de Reabertura de discussão de projeto de Sessão Legislativa anterior',
  },
  {
    cod: '343',
    sigla: 'REQ',
    nome: 'Requerimento de Transformação de Sessão Plenária em Comissão Geral',
  },
  {
    cod: '344',
    sigla: 'REQ',
    nome: 'Requerimento de Retificação de Ata',
  },
  {
    cod: '345',
    sigla: 'RPD',
    nome: 'Requerimento de Prorrogação de sessão',
    descricao: 'Prorrogação de sessão (Art. 72, RICD)',
  },
  {
    cod: '346',
    sigla: 'RPD',
    nome: 'Requerimento de Prorrogação da Ordem do Dia',
    descricao: 'Prorrogação da Ordem do Dia (Art. 84, RICD)',
  },
  {
    cod: '347',
    sigla: 'REQ',
    nome: 'Requerimento de Convocação de Sessões Extraordinarias para matérias constantes do ato de convocação',
  },
  {
    cod: '348',
    sigla: 'REQ',
    nome: 'Requerimento de Prorrogação de prazo de Comissão Temporária',
  },
  {
    cod: '349',
    sigla: 'REQ',
    nome: 'Requerimento de Constituição de Comissão Externa',
  },
  {
    cod: '350',
    sigla: 'REQ',
    nome: 'Requerimento de Realização de Sessão Extraordinária',
  },
  {
    cod: '351',
    sigla: 'REQ',
    nome: 'Requerimento de Realização de Sessão secreta',
  },
  {
    cod: '353',
    sigla: 'REQ',
    nome: 'Requerimento de Não realização de sessão solene em determinado dia',
  },
  {
    cod: '354',
    sigla: 'REQ',
    nome: 'Requerimento de Voto de regozijo ou louvor',
  },
  {
    cod: '355',
    sigla: 'REQ',
    nome: 'Requerimento de Voto de pesar',
  },
  {
    cod: '356',
    sigla: 'REQ',
    nome: 'Requerimento de Convocação de Ministro de Estado no Plenário (art. 50, CF)',
  },
  {
    cod: '357',
    sigla: 'REQ',
    nome: 'Requerimento de Quebra de sigilo (Requerimentos não especificados no RICD)',
  },
  {
    cod: '358',
    sigla: 'REQ',
    nome: 'Requerimento de Encaminha copia de Relatorio Final de C. Temporaria ',
  },
  {
    cod: '359',
    sigla: 'REQ',
    nome: 'Requerimento de Constituição de Comissão Especial de PEC',
  },
  {
    cod: '360',
    sigla: 'REQ',
    nome: 'Requerimento de Inserção nos Anais',
  },
  {
    cod: '361',
    sigla: 'REQ',
    nome: 'Requerimento de Publicação de documentos discursos de outro poder nao lidos na integra por deputado',
  },
  {
    cod: '362',
    sigla: 'REQ',
    nome: 'Requerimento de Adocão de providências em face da ausência de resposta no prazo constitucional a RIC',
    descricao: 'Art. 50, § 2º da CF c/c art. 105, RICD.',
  },
  {
    cod: '363',
    sigla: 'REQ',
    nome: 'Requerimento de Desarquivamento de Proposições',
  },
  {
    cod: '364',
    sigla: 'REQ',
    nome: 'Requerimento de Afastamento para tratamento de saude superior a 120 dias.',
    descricao: 'Art. 235, II, RICD.',
  },
  {
    cod: '365',
    sigla: 'REQ',
    nome: 'Requerimento de Afastamento para tratamento de saúde inferior a 120 dias.',
    descricao: 'Art. 235, II, RICD.',
  },
  {
    cod: '366',
    sigla: 'REQ',
    nome: 'Requerimento de Afastamento por licença de saude e consecutivamente afastamento para tratar de assunto particular superior a 120 dias.',
    descricao: 'Art. 235, II e III, RICD.',
  },
  {
    cod: '368',
    sigla: 'REQ',
    nome: 'Requerimento de Afastamento para investidura em cargo publico',
    descricao: 'Art. 56, inciso I da CF c/c com art. 235, IV, RICD.',
  },
  {
    cod: '369',
    sigla: 'REQ',
    nome: 'Requerimento de Prorrogação de licença para tratamento de saúde (licença superior a 120 dias)',
  },
  {
    cod: '370',
    sigla: 'REQ',
    nome: 'Requerimento de Interrupção da licença superior a 120 dias',
  },
  {
    cod: '371',
    sigla: 'REQ',
    nome: 'Requerimento de Justificativa de falta',
  },
  {
    cod: '372',
    sigla: 'REC',
    nome: 'Recurso contra devolução de requerimento de CPI (Art. 35, § 2º, RICD)',
    descricao: 'Contra devolução de requerimento de CPI (Art. 35, § 1º, RICD)',
  },
  {
    cod: '373',
    sigla: 'REC',
    nome: 'Recurso contra apreciação conclusiva de comissão (Art. 58, § 1º c/c art. 132, § 2º, RICD)',
    descricao: 'Contra apreciação conclusiva de comissão (Art. 58, § 1º, RICD)',
  },
  {
    cod: '374',
    sigla: 'REC',
    nome: 'Recurso contra apreciação conclusiva com pareceres contrarios (Art. 133, RICD)',
    descricao:
      'Contra apreciação conclusiva com pareceres contrarios (Art. 133, RICD)',
  },
  {
    cod: '375',
    sigla: 'REC',
    nome: 'Recurso contra parecer terminativo de comissão (Art. 132, § 2º c/c art. 144, caput, RICD)',
    descricao:
      'Contra parecer terminativo de comissão (Art. 132, § 2º c/c art. 144, caput, RICD)',
  },
  {
    cod: '376',
    sigla: 'REC',
    nome: 'Recurso contra devolução de proposição (Art. 137, § 2º, RICD)',
    descricao: 'Contra devolução de proposição (Art. 137, § 2º, RICD)',
  },
  {
    cod: '377',
    sigla: 'REC',
    nome: 'Recurso contra deferimento/indeferimento de audiencia (Art. 140, I, RICD)',
    descricao:
      'Contra deferimento/indeferimento de audiencia (Art. 140, I, RICD)',
  },
  {
    cod: '378',
    sigla: 'REC',
    nome: 'Recurso contra redistribuição de proposição (Art. 141, RICD)',
    descricao: 'Contra redistribuição de proposição (Art. 141, § 4º, RICD)',
  },
  {
    cod: '379',
    sigla: 'REC',
    nome: 'Recurso contra apensação/desapensação de proposição (Art. 142, I, RICD)',
    descricao:
      'Contra apensação/desapensação de proposição (Art. 142, I, RICD)',
  },
  {
    cod: '380',
    sigla: 'REC',
    nome: 'Recurso contra deferimento/indeferimento retirada proposição (Art. 104, caput, RICD)',
    descricao:
      'Contra deferimento/indeferimento retirada proposição (Art. 104, caput, RICD)',
  },
  {
    cod: '381',
    sigla: 'REC',
    nome: 'Recurso contra declaração de prejudicialidade. (Art. 164, § 2º, RICD)',
    descricao: 'Contra declaração de prejudicialidade. (Art. 164, § 2º, RICD)',
  },
  {
    cod: '382',
    sigla: 'REC',
    nome: 'Recurso contra decisão do Presidente da CD em Questao de Ordem (Art. 95, § 8º, RICD)',
    descricao:
      'Contra decisão do Presidente da CD em Questao de Ordem (Art. 95, § 8º, RICD)',
  },
  {
    cod: '383',
    sigla: 'REC',
    nome: 'Recurso contra decisão de Presidente de Comissão em Questão de Ordem (Art. 57, XXI c/c art. 17, III, f, RICD)',
    descricao:
      'Contra decisão de Presidente de Comissão em Questão de Ordem (Art. 57, XXI c/c art. 17, III, f, RICD)',
  },
  {
    cod: '384',
    sigla: 'REC',
    nome: 'Recurso contra indeferimento de Requerimento de Infomação (Art. 115, parágrafo único, RICD)',
    descricao:
      'Contra indeferimento de Requerimento de Infomação (Art. 115, parágrafo único, RICD)',
  },
  {
    cod: '385',
    sigla: 'REC',
    nome: 'Recurso contra nao recebimento de emenda (Art. 125, caput, RICD)',
    descricao: 'Contra nao recebimento de emenda (Art. 125, caput, RICD)',
  },
  {
    cod: '386',
    sigla: 'REC',
    nome: 'Recurso contra improcedencia de retificação de ata (Art. 80, § 1º, RICD)',
    descricao:
      'Contra improcedencia de retificação de ata (Art. 80, § 1º, RICD)',
  },
  {
    cod: '387',
    sigla: 'REC',
    nome: 'Recurso contra indeferimento de requerimento para publicação em ata (Art. 98, § 3º, RICD)',
    descricao:
      'Contra indeferimento de requerimento para publicação em ata (Art. 98, § 3º, RICD)',
  },
  {
    cod: '388',
    sigla: 'REC',
    nome: 'Recurso contra a não publicação de pronunciamento ou expressão (Art. 98, 6º, RICD)',
    descricao:
      'Contra a não publicação de pronunciamento ou expressão (Art. 98, 6º, RICD)',
  },
  {
    cod: '389',
    sigla: 'REC',
    nome: 'Recurso contra nao recebimento de denuncia crime responsabilidade (Art. 218, § 3º, RICD)',
    descricao:
      'Contra nao recebimento de denuncia crime responsabilidade (Art. 218, § 3º, RICD)',
  },
  {
    cod: '390',
    sigla: 'PLV',
    nome: 'Projeto de Lei de Conversão',
    descricao: 'Projeto de Lei de Conversão',
  },
  {
    cod: '391',
    sigla: 'REQ',
    nome: 'Requerimento de Urgência (Art. 154, II, do RICD)',
    descricao: 'Urgencia (Art. 154 do RICD)',
  },
  {
    cod: '392',
    sigla: 'REQ',
    nome: 'Requerimento de Urgência (Art. 155 do RICD)',
    descricao: 'Urgência (Art. 155 do RICD)',
  },
  {
    cod: '393',
    sigla: 'REQ',
    nome: 'Requerimento de Adiamento de discussão em regime de urgência',
    descricao:
      'Aditamento de discussão em regime de urgência nos termos do art. 177, §1º do RICD.',
  },
  {
    cod: '394',
    sigla: 'PDC',
    nome: 'Projeto de Decreto Legislativo de Medida Provisória',
    descricao: 'Medida Provisória (Art. 62, § 3º da CF)',
  },
  {
    cod: '395',
    sigla: 'PDC',
    nome: 'Projeto de Decreto Legislativo de Referendo ou Plebiscito',
    descricao: 'Plebiscito (Art. 49, XV da CF c/c o art. 3º Lei 9.709/98)',
  },
  {
    cod: '396',
    sigla: 'PDC',
    nome: 'Projeto de Decreto Legislativo de Concessão, Renovação e Permissão de Radio/TV',
    descricao: 'Concessão/Renovação de Radio/TV (Art. 49, XII c/c 223 da CF)',
  },
  {
    cod: '397',
    sigla: 'PDC',
    nome: 'Projeto de Decreto Legislativo de Acordos, tratados ou atos internacionais',
    descricao: 'Acordos, tratados ou atos internacionais (Art. 49, I da CF)',
  },
  {
    cod: '398',
    sigla: 'PDC',
    nome: 'Projeto de Decreto Legislativo de Indicação de Autoridade ao TCU',
    descricao: 'Indicação de Autoridade ao TCU (Art. 49, XIII da CF)',
  },
  {
    cod: '400',
    sigla: 'PRC',
    nome: 'Projeto de Resolução de Criação de CPI',
    descricao: 'Criação de CPI (Art. 35 do RICD)',
  },
  {
    cod: '401',
    sigla: 'MSC',
    nome: 'Mensagem de Concessão ou Renovação de Rádio e TV ',
    descricao: 'Concessão de Rádio e TV (Art. 49, XII c/c 223 CF)',
  },
  {
    cod: '402',
    sigla: 'REC',
    nome: 'Recurso contra aplicação de censura verbal (Art. 11, Parágrafo único do CEDP)',
    descricao:
      'Contra aplicação de censura verbal (Art. 11, Parágrafo único do CEDP)',
  },
  {
    cod: '403',
    sigla: 'MSC',
    nome: 'Mensagem de Comunica ausência do país',
    descricao: 'Comunica ausência do país',
  },
  {
    cod: '404',
    sigla: 'MSC',
    nome: 'Mensagem de Cancelamento de Urgência',
    descricao: 'Cancelamento de Urgência',
  },
  {
    cod: '405',
    sigla: 'MSC',
    nome: 'Mensagem de Retirada de proposição',
    descricao: 'Retirada de proposição',
  },
  {
    cod: '406',
    sigla: 'MSC',
    nome: 'Mensagem de Solicitação de urgência ',
    descricao: 'Solicitação de urgência ',
  },
  {
    cod: '407',
    sigla: 'PDC',
    nome: 'Projeto de Decreto Legislativo de Programação Monetária',
    descricao: 'Programação Monetária (Lei nº 9.069/95)',
  },
  {
    cod: '408',
    sigla: 'PDC',
    nome: 'Projeto de Decreto Legislativo de Sustação de Atos Normativos do Poder Executivo',
    descricao: 'Susta atos normativos do Poder Executivo.',
  },
  {
    cod: '409',
    sigla: 'AV',
    nome: 'Demonstrativo de emissão do real',
    descricao: 'Demonstrativo de emissão do real (Lei nº 9.069/95)',
  },
  {
    cod: '410',
    sigla: 'MSC',
    nome: 'Mensagem de Indicação de Líder',
    descricao: 'Indicação de Líder',
  },
  {
    cod: '411',
    sigla: 'MSC',
    nome: 'Mensagem de Acordos, convênios, tratados e atos internacionais',
    descricao: 'Acordos, convênios, tratados e atos internacionais',
  },
  {
    cod: '412',
    sigla: 'MSC',
    nome: 'Mensagem de Restituição de Autógrafos',
    descricao: 'Restituição de Autógrafos',
  },
  {
    cod: '413',
    sigla: 'REQ',
    nome: 'Requerimento de Retirada de proposição sem parecer',
  },
  {
    cod: '414',
    sigla: 'MSC',
    nome: 'Mensagem de ausência do país por mais de 15 dias ',
    descricao:
      'Mensagem de ausência do país por mais de 15 dias (Art. 49, III, CF)',
  },
  {
    cod: '415',
    sigla: 'MSC',
    nome: 'Mensagem de ausência do país por menos de 15 dias  ',
    descricao:
      'Mensagem de ausência do país por menos de 15 dias  (Art. 49, III, CF)',
  },
  {
    cod: '417',
    sigla: 'TVR',
    nome: 'Autorização - Rádio Comunitária',
    descricao: 'Autorização - Rádio Comunitária',
  },
  {
    cod: '418',
    sigla: 'TVR',
    nome: 'Concessão - Rádio Ondas Curtas',
    descricao: 'Concessão - Rádio Ondas Curtas',
  },
  {
    cod: '419',
    sigla: 'TVR',
    nome: 'Concessão - Rádio Ondas Médias',
    descricao: 'Concessão - Rádio Ondas Médias',
  },
  {
    cod: '420',
    sigla: 'TVR',
    nome: 'Concessão Rádio Ondas Médias Educativa',
    descricao: 'Concessão Rádio Ondas Médias Educativa',
  },
  {
    cod: '421',
    sigla: 'TVR',
    nome: 'Concessão Rádio Ondas Tropicais',
    descricao: 'Concessão Rádio Ondas Tropocais',
  },
  {
    cod: '422',
    sigla: 'TVR',
    nome: 'Concessão Radiodifusão Sons e Imagens',
    descricao: 'Concessão Radiodifusão Sons e Imagens',
  },
  {
    cod: '423',
    sigla: 'TVR',
    nome: 'Concessão TV Educativa',
    descricao: 'Concessão TV Educativa',
  },
  {
    cod: '424',
    sigla: 'TVR',
    nome: 'Permissão Frequência Modulada Educativa',
    descricao: 'Permissão Frequência Modulada Educativa',
  },
  {
    cod: '425',
    sigla: 'TVR',
    nome: 'Permissão Rádio Frequência Modulada',
    descricao: 'Permissão Rádio Frequência Modulada',
  },
  {
    cod: '426',
    sigla: 'TVR',
    nome: 'Permissão Rádio Ondas Médias Local',
    descricao: 'Permissão Rádio Ondas Médias Local',
  },
  {
    cod: '427',
    sigla: 'TVR',
    nome: 'Renovação Rádio Comunitária',
    descricao: 'Renovação Rádio Comunitária',
  },
  {
    cod: '428',
    sigla: 'TVR',
    nome: 'Renovação Rádio Frequência Modulada',
    descricao: 'Renovação Rádio Frequência Modulada',
  },
  {
    cod: '429',
    sigla: 'TVR',
    nome: 'Renovação Rádio Frequência Modulada Educativa',
    descricao: 'Renovação Rádio Frequência Modulada Educativa',
  },
  {
    cod: '430',
    sigla: 'TVR',
    nome: 'Renovação Rádio Ondas Curtas',
    descricao: 'Renovação Rádio Ondas Curtas',
  },
  {
    cod: '431',
    sigla: 'TVR',
    nome: 'Renovação Rádio Ondas Médias',
    descricao: 'Renovação Rádio Ondas Médias',
  },
  {
    cod: '432',
    sigla: 'TVR',
    nome: 'Renovação Rádio Ondas Médias Local',
    descricao: 'Renovação Rádio Ondas Médias Local',
  },
  {
    cod: '433',
    sigla: 'TVR',
    nome: 'Renovação Rádio Ondas Médias Educativa',
    descricao: 'Renovação Rádio Ondas Médias Educativa',
  },
  {
    cod: '434',
    sigla: 'TVR',
    nome: 'Renovação Rádio Ondas Tropicais',
    descricao: 'Renovação  Rádio Ondas Tropicais',
  },
  {
    cod: '435',
    sigla: 'TVR',
    nome: 'Renovação TV Sons e Imagens',
    descricao: 'Renovação TV Sons e Imagens',
  },
  {
    cod: '436',
    sigla: 'TVR',
    nome: 'Renovação TV Educativa',
    descricao: 'Renovação TV Educativa',
  },
  {
    cod: '437',
    sigla: 'MSC',
    nome: 'Mensagem de Cumprimento de meta',
    descricao: 'Cumprimento de meta',
  },
  {
    cod: '439',
    sigla: 'DCR',
    nome: 'Denúncia por Crime de Responsabilidade',
    descricao: 'Denúncia por crime de responsabilidade',
  },
  {
    cod: '440',
    sigla: '',
    nome: 'J) NÃO PROPOSIÇÃO',
    descricao: 'Não Proposição',
  },
  {
    cod: '441',
    sigla: 'REQ',
    nome: 'Requerimento de Moção',
  },
  {
    cod: '442',
    sigla: 'PEP',
    nome: 'Parecer às Emendas de Plenário',
  },
  {
    cod: '443',
    sigla: 'PSS',
    nome: 'Parecer às Emendas ou ao Substitutivo do Senado',
  },
  {
    cod: '444',
    sigla: 'PRC',
    nome: 'Projeto de Resolução de Alteração do Regimento e outros',
  },
  {
    cod: '445',
    sigla: 'NIC',
    nome: 'Norma Interna',
  },
  {
    cod: '448',
    sigla: 'REQ',
    nome: 'Requerimento (Outros)',
  },
  {
    cod: '449',
    sigla: 'MSC',
    nome: 'Mensagem de Implementação da Lei 10.147/00',
  },
  {
    cod: '450',
    sigla: 'ERD',
    nome: 'Emenda de Redação',
  },
  {
    cod: '451',
    sigla: 'PPR',
    nome: 'Parecer Reformulado de Plenário',
  },
  {
    cod: '452',
    sigla: 'TER',
    nome: 'Termo de Implementação',
  },
  {
    cod: '453',
    sigla: 'RLP',
    nome: 'Relatório Prévio',
  },
  {
    cod: '454',
    sigla: 'PDC',
    nome: 'Projeto de Decreto Legislativo de Perempção da Concessão',
  },
  {
    cod: '455',
    sigla: 'RLF',
    nome: 'Relatório Final',
  },
  {
    cod: '456',
    sigla: 'PRT',
    nome: 'Parecer Técnico',
  },
  {
    cod: '457',
    sigla: 'PRO',
    nome: 'Proposta',
  },
  {
    cod: '459',
    sigla: 'REC',
    nome: 'Recurso contra decisão de presidente de Comissão em Reclamação (Art. 96, § 2º, RICD)',
  },
  {
    cod: '460',
    sigla: 'OBJ',
    nome: 'Objeto de Deliberação',
  },
  {
    cod: '461',
    sigla: 'MSC',
    nome: 'Mensagem de Missão de Paz (Art. 15 da LC 97/99)',
    descricao: 'Art. 15 da Lei Complementar nº 97/99',
  },
  {
    cod: '462',
    sigla: '',
    nome: 'I) OUTROS ITENS SUJEITOS À DELIBERAÇÃO',
  },
  {
    cod: '463',
    sigla: '',
    nome: 'G) PROPOSIÇÔES CN E SF TRAMITANDO NA CÂMARA (CMO E MERCOSUL)',
  },
  {
    cod: '464',
    sigla: 'PLS',
    nome: 'Projeto de Lei do Senado Federal',
  },
  {
    cod: '465',
    sigla: 'PLC',
    nome: 'Projeto de Lei da Câmara dos Deputados (SF)',
  },
  {
    cod: '466',
    sigla: 'PDS',
    nome: 'Projeto de Decreto Legislativo (SF)',
  },
  {
    cod: '467',
    sigla: 'RPD',
    nome: 'Requerimento de Adiamento de Votação de Matéria Urgente',
    descricao:
      'Adiamento de Votação em Regime de Urgência, nos termos do art. 177, § 1º do RICD.',
  },
  {
    cod: '468',
    sigla: 'RPD',
    nome: 'Requerimento de Encerramento da Discussão em Comissão',
  },
  {
    cod: '482',
    sigla: 'RDV',
    nome: 'Redação do Vencido',
  },
  {
    cod: '483',
    sigla: 'RST',
    nome: 'Redação para o segundo turno',
  },
  {
    cod: '484',
    sigla: 'RLP(R)',
    nome: 'Relatório Prévio Reformulado',
  },
  {
    cod: '485',
    sigla: 'PDC',
    nome: 'Projeto de Decreto Legislativo de Aprovação de Contas dos Presidentes',
  },
  {
    cod: '486',
    sigla: 'RPD',
    nome: 'Requerimento Procedimental de Sessão/Reunião',
  },
  {
    cod: '487',
    sigla: 'EPP',
    nome: 'Emenda ao Plano Plurianual',
    descricao: 'Emenda ao Plano Plurianual',
  },
  {
    cod: '488',
    sigla: 'EAG',
    nome: 'Emenda Substitutiva Aglutinativa Global',
  },
  {
    cod: '489',
    sigla: 'MSC',
    nome: 'Mensagem que Propõe alteração a Projeto',
  },
  {
    cod: '490',
    sigla: 'PEA',
    nome: 'Parecer à Emenda Aglutinativa',
  },
  {
    cod: '491',
    sigla: 'SPA',
    nome: 'Sugestão de Emenda ao PPA - CLP',
  },
  {
    cod: '492',
    sigla: 'TVR',
    nome: 'Autorização - Rádio Comunitária - Dez anos',
    descricao: 'Autorização - Rádio Comunitária - Dez anos',
  },
  {
    cod: '493',
    sigla: 'MSC',
    nome: 'Mensagem de Perempção de Rádio/TV',
  },
  {
    cod: '494',
    sigla: 'PDC',
    nome: 'Projeto de Decreto Legislativo de Alteração de Decreto Legislativo',
  },
  {
    cod: '495',
    sigla: 'AV',
    nome: 'Aviso',
  },
  {
    cod: '496',
    sigla: 'IAN',
    nome: 'Indicação da ANC (1987-88)',
  },
  {
    cod: '497',
    sigla: 'OF',
    nome: 'Ofício Externo',
  },
  {
    cod: '498',
    sigla: 'PCA',
    nome: 'Parecer da ANC (1987-88)',
  },
  {
    cod: '499',
    sigla: 'PDA',
    nome: 'Projeto de Decisão da ANC (1987-88)',
  },
  {
    cod: '500',
    sigla: 'PDC',
    nome: 'Projeto de Decreto Legislativo de Autorização do Congresso Nacional',
  },
  {
    cod: '501',
    sigla: 'PRA',
    nome: 'Projeto de Resolução da ANC (1987-88)',
  },
  {
    cod: '503',
    sigla: 'RCM',
    nome: 'Requerimento de Comissão Mista',
  },
  {
    cod: '504',
    sigla: 'RQA',
    nome: 'Requerimento de Informações da ANC (1987-88)',
  },
  {
    cod: '505',
    sigla: 'RQC',
    nome: 'Requerimento de Convocação',
  },
  {
    cod: '506',
    sigla: 'AA',
    nome: 'Autógrafo',
  },
  {
    cod: '507',
    sigla: 'REC',
    nome: 'Recurso contra Inadmissibilidade de PEC (Art. 202, § 1º do RICD)',
  },
  {
    cod: '508',
    sigla: 'ESP',
    nome: 'Emenda Substitutiva de Plenário',
  },
  {
    cod: '509',
    sigla: 'SSP',
    nome: 'Subemenda Substitutiva de Plenário',
  },
  {
    cod: '513',
    sigla: 'MSC',
    nome: 'Mensagem de Implementação da Lei 10.707/03',
  },
  {
    cod: '514',
    sigla: 'PDC',
    nome: 'Projeto de Decreto Legislativo de Ministro do TCU',
  },
  {
    cod: '515',
    sigla: '',
    nome: 'K) PROPOSIÇÕES INATIVAS IMPORTADAS SINOPSE',
  },
  {
    cod: '516',
    sigla: 'REQ',
    nome: 'Requerimento de Inclusão na Ordem do Dia de proposição (com previsão ou durante o período de Convocação Extraordinário)',
  },
  {
    cod: '517',
    sigla: 'REQ',
    nome: 'Requerimento de Interrupção da licença inferior a 120 dias',
  },
  {
    cod: '518',
    sigla: 'RPD',
    nome: 'Requerimento de Votação em globo dos destaques simples',
  },
  {
    cod: '519',
    sigla: 'REQ',
    nome: 'Requerimento de Afastamento para missão temporária de caráter diplomático ou cultural',
  },
  {
    cod: '520',
    sigla: 'REQ',
    nome: 'Requerimento de Constituição de Comissão Especial de Projeto de Código',
  },
  {
    cod: '521',
    sigla: 'REQ',
    nome: 'Requerimento de Constituição de Comissão Especial de Projeto',
  },
  {
    cod: '522',
    sigla: 'REQ',
    nome: 'Requerimento de Constituição de Comissão Especial de Estudo',
  },
  {
    cod: '523',
    sigla: 'REQ',
    nome: 'Requerimento de Convocação de Ministro de Estado na Comissão (art. 50, CF)',
  },
  {
    cod: '524',
    sigla: 'REQ',
    nome: 'Requerimento de Convocação de Sessão Extraordinária do CN',
  },
  {
    cod: '525',
    sigla: 'REQ',
    nome: 'Requerimento de Convocação de reunião extraordinária de comissão',
  },
  {
    cod: '526',
    sigla: 'REQ',
    nome: 'Requerimento de Destaque votação de emenda ou parte',
  },
  {
    cod: '527',
    sigla: 'REQ',
    nome: 'Requerimento de Destaque para votação de subemenda ou parte',
  },
  {
    cod: '528',
    sigla: 'REQ',
    nome: 'Requerimento de Destaque para tornar parte de emenda ou proposição projeto autonomo',
  },
  {
    cod: '529',
    sigla: 'REQ',
    nome: 'Requerimento de Destaque para votação de projeto ou substitutivo ou parte deles quando a preferencia cair sobre outro ou sobre proposições apensadas',
  },
  {
    cod: '530',
    sigla: 'REQ',
    nome: 'Requerimento de Destaque para votação de parte da proposição',
  },
  {
    cod: '531',
    sigla: 'RPD',
    nome: 'Requerimento de Prorrogação da sessão para discussão e votação da matéria da Ordem do Dia',
  },
  {
    cod: '532',
    sigla: 'RPD',
    nome: 'Requerimento de Prorrogação da sessão para audiência de Ministro de Estado',
  },
  {
    cod: '533',
    sigla: 'RPD',
    nome: 'Requerimento de Prorrogação da sessão para realização de homenagens',
  },
  {
    cod: '534',
    sigla: 'REQ',
    nome: 'Requerimento de Prorrogação de licença para tratamento de saúde (Licença inferior a 120 dias)',
  },
  {
    cod: '535',
    sigla: 'MMP',
    nome: 'Mensagem (MPU)',
  },
  {
    cod: '536',
    sigla: 'RIN',
    nome: 'Requerimento de Resolução Interna',
  },
  {
    cod: '537',
    sigla: 'MST',
    nome: 'Mensagem (STF)',
  },
  {
    cod: '538',
    sigla: 'APJ',
    nome: 'Anteprojeto',
  },
  {
    cod: '539',
    sigla: 'RQN',
    nome: 'Requerimento do Congresso Nacional',
    descricao:
      'Solicitação feita pela Claudia da SGM em 30/05/2005 as 18:14 (Incluído por MarcoRuas).\r\nRequerimento do Congresso nacional que servirá de suporte aos recursos R.C (novos recursos). ',
  },
  {
    cod: '540',
    sigla: 'R.C',
    nome: 'Recurso do Congresso Nacional',
    descricao:
      'Solicitação feita pela Claudia da SGM em 30/05/2005 as 18:14 (Incluído por MarcoRuas).\r\nOs recursos existente em RCN serão transferidos para este novo código.',
  },
  {
    cod: '541',
    sigla: 'MSC',
    nome: 'Mensagem de Tranferência de Controle Societário',
  },
  {
    cod: '550',
    sigla: 'PDL',
    nome: 'Projeto de Decreto Legislativo',
    descricao: 'Projeto de Decreto Legislativo',
  },
  {
    cod: '551',
    sigla: 'PDL',
    nome: 'Projeto de Decreto Legislativo de Medida Provisória',
    descricao: 'Medida Provisória (Art. 62, § 3º da CF)',
  },
  {
    cod: '552',
    sigla: 'PDL',
    nome: 'Projeto de Decreto Legislativo de Referendo ou Plebiscito',
    descricao: 'Plebiscito (Art. 49, XV da CF c/c o art. 3º Lei 9.709/98)',
  },
  {
    cod: '553',
    sigla: 'PDL',
    nome: 'Projeto de Decreto Legislativo de Concessão, Renovação e Permissão de Radio/TV',
    descricao: 'Concessão/Renovação de Radio/TV (Art. 49, XII c/c 223 da CF)',
  },
  {
    cod: '554',
    sigla: 'PDL',
    nome: 'Projeto de Decreto Legislativo de Acordos, tratados ou atos internacionais',
    descricao: 'Acordos, tratados ou atos internacionais (Art. 49, I da CF)',
  },
  {
    cod: '555',
    sigla: 'PDL',
    nome: 'Projeto de Decreto Legislativo de Indicação de Autoridade ao TCU',
    descricao: 'Indicação de Autoridade ao TCU (Art. 49, XIII da CF)',
  },
  {
    cod: '556',
    sigla: 'PDL',
    nome: 'Projeto de Decreto Legislativo de Programação Monetária',
    descricao: 'Programação Monetária (Lei nº 9.069/95)',
  },
  {
    cod: '557',
    sigla: 'PDL',
    nome: 'Projeto de Decreto Legislativo de Sustação de Atos Normativos do Poder Executivo',
    descricao: 'Susta atos normativos do Poder Executivo.',
  },
  {
    cod: '558',
    sigla: 'PDL',
    nome: 'Projeto de Decreto Legislativo de Perempção da Concessão',
  },
  {
    cod: '559',
    sigla: 'PDL',
    nome: 'Projeto de Decreto Legislativo de Aprovação de Contas dos Presidentes',
  },
  {
    cod: '560',
    sigla: 'PDL',
    nome: 'Projeto de Decreto Legislativo de Alteração de Decreto Legislativo',
  },
  {
    cod: '561',
    sigla: 'PDL',
    nome: 'Projeto de Decreto Legislativo de Autorização do Congresso Nacional',
  },
  {
    cod: '562',
    sigla: 'PDL',
    nome: 'Projeto de Decreto Legislativo de Ministro do TCU',
  },
  {
    cod: '563',
    sigla: 'PDL',
    nome: 'Projeto de Decreto Legislativo de Perempção',
  },
  {
    cod: '600',
    sigla: 'CCN',
    nome: 'Consulta do Congresso Nacional',
    descricao:
      'Solicitação feita pela Claudia da SGM em 31/05/2005 as 14:30 (Incluído por MarceloLapa).\r\n',
  },
  {
    cod: '601',
    sigla: 'PDC',
    nome: 'Projeto de Decreto Legislativo de Perempção',
  },
  {
    cod: '602',
    sigla: 'MSC',
    nome: 'Mensagem Revogação ou Anulação de Portaria',
  },
  {
    cod: '603',
    sigla: 'ADD',
    nome: 'Adendo',
  },
  {
    cod: '604',
    sigla: 'DEC',
    nome: 'Decisão',
  },
  {
    cod: '605',
    sigla: 'ATC',
    nome: 'Ato Convocatório',
  },
  {
    cod: '606',
    sigla: 'PRST',
    nome: 'Parecer à Redação para o Segundo Turno',
  },
  {
    cod: '607',
    sigla: 'RLP(V)',
    nome: 'Relatório Prévio Vencedor',
  },
  {
    cod: '608',
    sigla: 'EMA',
    nome: 'Emenda Aglutinativa de Plenário',
  },
  {
    cod: '609',
    sigla: 'REQ',
    nome: 'Requerimento de Criação de Frente Parlamentar',
  },
  {
    cod: '610',
    sigla: 'DOC',
    nome: 'Documento',
  },
  {
    cod: '611',
    sigla: 'SOR',
    nome: 'Sugestão de Emenda ao Orçamento - Comissões',
  },
  {
    cod: '612',
    sigla: 'SLD',
    nome: 'Sugestão de Emenda à LDO - Comissões',
  },
  {
    cod: '613',
    sigla: 'SPP',
    nome: 'Sugestão de Emenda ao PPA - Comissões',
  },
  {
    cod: '614',
    sigla: 'RPA',
    nome: 'Relatório Parcial',
  },
  {
    cod: '615',
    sigla: 'MTC',
    nome: 'Mensagem (TCU)',
  },
  {
    cod: '616',
    sigla: 'SPP-R',
    nome: 'Sugestão de Emenda ao PPA - revisão (Comissões)',
  },
  {
    cod: '617',
    sigla: 'SPA-R',
    nome: 'Sugestão de Emenda ao PPA - revisão (CLP)',
  },
  {
    cod: '618',
    sigla: 'REC',
    nome: 'Recurso do Conselho de Ética que contraria norma constitucional ou regimental (Art. 13 ou 14, CEDP)',
  },
  {
    cod: '619',
    sigla: 'RFP',
    nome: 'Refomulação de Parecer - art. 130, parágrafo único do RICD.',
  },
  {
    cod: '620',
    sigla: 'PPP',
    nome: 'Parecer Proferido em Plenário - Notas Taquigráficas',
  },
  {
    cod: '621',
    sigla: 'PSS',
    nome: 'Parecer às Emendas ou ao Substitutivo do Senado - Notas Taquigráficas',
  },
  {
    cod: '622',
    sigla: 'PRVP',
    nome: 'Proposta de Redação do Vencido em Primeiro Turno',
  },
  {
    cod: '623',
    sigla: 'MSC',
    nome: 'Mensagem de Afastamento/Interrupção de tratamento de saúde',
  },
  {
    cod: '624',
    sigla: 'SUC',
    nome: 'Sugestão a Projeto de Consolidação de Leis',
  },
  {
    cod: '625',
    sigla: 'REQ',
    nome: 'Requerimento de Prejudicialidade',
  },
  {
    cod: '626',
    sigla: 'MSC',
    nome: 'Mensagem de Cessão de Imóvel',
  },
  {
    cod: '627',
    sigla: 'TVR',
    nome: 'Perempção de Rádio/TV',
  },
  {
    cod: '628',
    sigla: 'TVR',
    nome: 'Revogação ou Anulação de Portaria de Rádio/TV',
  },
  {
    cod: '629',
    sigla: 'TVR',
    nome: 'Transferência de Controle Societário',
  },
  {
    cod: '630',
    sigla: 'REC',
    nome: 'Recurso contra indeferimento liminar de emenda à Medida Provisória (Art. 125, caput, RICD)',
  },
  {
    cod: '631',
    sigla: 'REL',
    nome: 'Relatório de Comissão Externa',
  },
  {
    cod: '632',
    sigla: 'PLN',
    nome: 'Projeto de Lei (CN)',
  },
  {
    cod: '633',
    sigla: 'PLN',
    nome: 'Projeto de Lei (CN) de Alteração do PPA e LDO',
  },
  {
    cod: '634',
    sigla: 'PDN',
    nome: 'Projeto de Decreto Legislativo (CN)',
  },
  {
    cod: '635',
    sigla: 'AVN',
    nome: 'Aviso (CN)',
  },
  {
    cod: '636',
    sigla: 'AVN',
    nome: 'Aviso (CN) de Relatório de Atividades do TCU',
  },
  {
    cod: '637',
    sigla: 'AVN',
    nome: 'Aviso (CN) de Relatório de Gestão Fiscal',
  },
  {
    cod: '638',
    sigla: 'AVN',
    nome: 'Aviso (CN) de Demonstrações Financeiras do Banco Central do Brasil',
  },
  {
    cod: '639',
    sigla: 'AVN',
    nome: 'Aviso (CN) de Contas do Governo da República',
  },
  {
    cod: '640',
    sigla: 'AVN',
    nome: 'Aviso (CN) de Relatório de Desempenho do Fundo Soberano do Brasil',
  },
  {
    cod: '641',
    sigla: 'AVN',
    nome: 'Aviso (CN) de Subtítulos com Indícios de Irregularidades Graves Apontadas pelo TCU',
  },
  {
    cod: '642',
    sigla: 'AVN',
    nome: 'Aviso (CN) de Operações de Redesconto e Empréstimo realizadas pelo Banco Central',
  },
  {
    cod: '643',
    sigla: 'MCN',
    nome: 'Mensagem (CN)',
  },
  {
    cod: '644',
    sigla: 'OFN',
    nome: 'Ofício (CN)',
  },
  {
    cod: '645',
    sigla: 'MCN',
    nome: 'Mensagem (CN) de Relatório de Avaliação do Cumprimento das Metas Fiscais/Superávit Primário, MCN',
  },
  {
    cod: '646',
    sigla: 'MCN',
    nome: 'Mensagem (CN) de Relatório de Gestão Fiscal, MCN',
  },
  {
    cod: '647',
    sigla: 'MCN',
    nome: 'Mensagem (CN) de Operações de Crédito Incluídas na LOA Pedentes de Contratação, MCN',
  },
  {
    cod: '648',
    sigla: 'MCN',
    nome: 'Mensagem (CN) de Relatório de Avaliação do PPA, MCN',
  },
  {
    cod: '649',
    sigla: 'MCN',
    nome: 'Mensagem (CN) de Contas do Governo da República, MCN',
  },
  {
    cod: '650',
    sigla: 'MCN',
    nome: 'Mensagem (CN) de Relatório de Avaliação de Receitas e Despesas, MCN',
  },
  {
    cod: '651',
    sigla: 'OFN',
    nome: 'Ofício (CN) de Relatório de Gestão Fiscal',
  },
  {
    cod: '652',
    sigla: 'OFN',
    nome: 'Ofício (CN) de Relatório Trimestral Gerencial do BNDES',
  },
  {
    cod: '653',
    sigla: 'OFN',
    nome: 'Ofício (CN) de Operações de Empréstimo de Capital de Giro Contratadas pela Caixa Econômica Federal',
  },
  {
    cod: '654',
    sigla: 'OFN',
    nome: 'Ofício (CN) de Demonstrações Contábeis de Fundo Constitucional de Financiamento',
  },
  {
    cod: '655',
    sigla: 'OFN',
    nome: 'Ofício (CN) de Contas do Governo da República',
  },
  {
    cod: '656',
    sigla: 'OFN',
    nome: 'Ofício (CN) de Subtítulos com Indícios de Irregularidades Graves apontadas pelo TCU',
  },
  {
    cod: '657',
    sigla: 'PLN',
    nome: 'Projeto de Lei (CN) de Crédito Especial',
  },
  {
    cod: '658',
    sigla: 'PLN',
    nome: 'Projeto de Lei (CN) de Crédito Suplementar',
  },
  {
    cod: '659',
    sigla: 'PLN',
    nome: 'Projeto de Lei (CN) de Lei Orçamentária Anual (LOA)',
  },
  {
    cod: '660',
    sigla: 'PLN',
    nome: 'Projeto de Lei (CN) de Lei de Diretrizes Orçamentárias (LDO)',
  },
  {
    cod: '661',
    sigla: 'PLN',
    nome: 'Projeto de Lei (CN) de Plano Plurianual',
  },
  {
    cod: '662',
    sigla: 'MSF',
    nome: 'Mensagem (SF)',
  },
  {
    cod: '663',
    sigla: 'PRP',
    nome: 'Parecer do Relator Parcial',
  },
  {
    cod: '664',
    sigla: 'REQ',
    nome: 'Requerimento de Retirada de Emenda a Medida Provisória',
  },
  {
    cod: '665',
    sigla: 'EMRP',
    nome: 'Emenda de Relator Parcial',
  },
  {
    cod: '666',
    sigla: 'CAC',
    nome: 'Comunicado de Alteração do Controle Societário',
  },
  {
    cod: '667',
    sigla: 'RRL',
    nome: 'Relatório do Relator (CMO)',
  },
  {
    cod: '668',
    sigla: 'CVR',
    nome: 'Contestação ao Voto do Relator',
  },
  {
    cod: '669',
    sigla: 'PARF',
    nome: 'Parecer de Comissão para Redação Final',
  },
  {
    cod: '670',
    sigla: 'MPV',
    nome: 'Medida Provisória de Crédito Extraordinário',
  },
  {
    cod: '671',
    sigla: 'OFN',
    nome: 'Ofício (CN) de Relatório de Atividades da Autoridade Pública Olímpica - APO',
  },
  {
    cod: '672',
    sigla: 'AVN',
    nome: 'Aviso (CN) de Relatório de Gestão Fiscal do Tribunal de Contas da União',
  },
  {
    cod: '673',
    sigla: 'OFN',
    nome: 'Ofício (CN) de Lei de Incentivo ao Esporte',
  },
  {
    cod: '674',
    sigla: 'SRL',
    nome: 'Sugestão de Emenda a Relatório',
  },
  {
    cod: '675',
    sigla: 'RPL',
    nome: 'Relatório Preliminar',
  },
  {
    cod: '676',
    sigla: 'RRC',
    nome: 'Relatório de Receita',
  },
  {
    cod: '679',
    sigla: 'RPLE',
    nome: 'Relatório Preliminar Apresentado com Emendas',
  },
  {
    cod: '680',
    sigla: 'ERR',
    nome: 'Errata',
  },
  {
    cod: '681',
    sigla: 'CAE',
    nome: 'Relatório de Atividades do Comitê de Admissibilidade de Emendas (CAE)',
  },
  {
    cod: '682',
    sigla: 'COI',
    nome: 'Relatório do COI',
  },
  {
    cod: '683',
    sigla: 'RAT',
    nome: 'Relatório Setorial',
  },
  {
    cod: '685',
    sigla: 'CAE',
    nome: 'Relatório do CAE',
  },
  {
    cod: '686',
    sigla: 'REQ',
    nome: 'Requerimento para realização ou participação em Seminário, Visita Técnica ou outro Evento',
  },
  {
    cod: '687',
    sigla: 'REQ',
    nome: 'Requerimento de Reapresentação de Projeto de Lei Rejeitado na mesma Sessão Legislativa',
  },
  {
    cod: '688',
    sigla: 'RPD',
    nome: 'Requerimento de Inclusão de Matéria na Ordem do Dia para Apreciação Imediata na Comissão',
  },
  {
    cod: '689',
    sigla: 'OFN',
    nome: 'Ofício (CN) de Informações de Execução das Obras do PAC',
  },
  {
    cod: '690',
    sigla: 'OFS',
    nome: 'Ofício do Senado Federal',
  },
  {
    cod: '691',
    sigla: 'OFS',
    nome: 'Ofício do Senado Federal de Fundo Constitucional de Financiamento ',
  },
  {
    cod: '692',
    sigla: 'PLN',
    nome: 'Projeto de Lei (CN) de Alteração da LDO',
  },
  {
    cod: '693',
    sigla: 'PLN',
    nome: 'Projeto de Lei (CN) de Alteração da LOA',
  },
  {
    cod: '694',
    sigla: 'MSG',
    nome: 'Mensagem (SF)',
  },
  {
    cod: '695',
    sigla: 'MSG',
    nome: 'Mensagem (SF) de Contas do Governo da República',
  },
  {
    cod: '696',
    sigla: 'OFN',
    nome: 'Ofício (CN) de Demonstrações Contábeis do Fundo Constitucional de Financiamento do Norte (FNO)',
  },
  {
    cod: '697',
    sigla: 'OFN',
    nome: 'Ofício (CN) de Demonstrações Contábeis do Fundo Constitucional de Financiamento do Centro-Oeste (FCO)',
  },
  {
    cod: '698',
    sigla: 'OFN',
    nome: 'Ofício (CN) de Demonstrações Contábeis do Fundo Constitucional de Financiamento do Nordeste (FNE).',
  },
  {
    cod: '699',
    sigla: 'PLN',
    nome: 'Projeto de Lei (CN) de Alteração do PPA',
  },
  {
    cod: '700',
    sigla: '',
    nome: 'Outras Proposições - Comissão Mista',
  },
  {
    cod: '701',
    sigla: 'SBT-A',
    nome: 'Substitutivo adotado pela Comissão',
  },
  {
    cod: '702',
    sigla: 'EMC-A',
    nome: 'Emenda Adotada pela Comissão',
  },
  {
    cod: '703',
    sigla: 'SBE-A',
    nome: 'Subemenda Adotada pela Comissão',
  },
  {
    cod: '704',
    sigla: 'RPLOA',
    nome: 'Relatório Preliminar',
  },
  {
    cod: '705',
    sigla: 'ANEXO',
    nome: 'Anexo',
  },
  {
    cod: '706',
    sigla: 'EMPV',
    nome: 'Emenda à Medida Provisória (CN)',
  },
  {
    cod: '707',
    sigla: 'REL',
    nome: 'Relatório do Congresso Nacional',
  },
  {
    cod: '708',
    sigla: 'OF',
    nome: 'Ofício do Congresso Nacional',
  },
  {
    cod: '709',
    sigla: 'SBR',
    nome: 'Subemenda de Relator',
  },
  {
    cod: '710',
    sigla: 'AVN',
    nome: 'Aviso (CN) de Contas do Gestor Federal do SUS',
  },
  {
    cod: '711',
    sigla: 'OFN',
    nome: 'Ofício (CN) de Demonstrações Financeiras do Banco Central do Brasil',
  },
  {
    cod: '712',
    sigla: 'AVN',
    nome: 'Aviso (CN) de Contas do TCU',
  },
  {
    cod: '713',
    sigla: 'ERD-A',
    nome: 'Emenda de Redação Adotada',
  },
  {
    cod: '714',
    sigla: 'PIN',
    nome: 'Proposta de Instrução Normativa',
  },
  {
    cod: '715',
    sigla: 'OFN',
    nome: 'Ofício (CN) de Contas do TCU',
  },
  {
    cod: '720',
    sigla: 'PROC',
    nome: 'Processo Interno',
    descricao: 'Documento Processo Interno',
  },
  {
    cod: '810',
    sigla: 'ATA',
    nome: 'Ata',
  },
  {
    cod: '814',
    sigla: 'CRVITAEDOC',
    nome: 'Curriculum Vitae/Outro Documento',
    descricao: null,
  },
  {
    cod: '822',
    sigla: 'OF',
    nome: 'Ofício do Congresso Nacional',
  },
  {
    cod: '823',
    sigla: 'OF',
    nome: 'Ofício do Senado Federal',
  },
  {
    cod: '830',
    sigla: 'PR/CNMP',
    nome: 'Parecer do Conselho Nacional do Ministério Público',
    descricao: null,
  },
  {
    cod: '831',
    sigla: 'PR/CNJ',
    nome: 'Parecer do Conselho Nacional de Justiça',
    descricao: null,
  },
  {
    cod: '832',
    sigla: 'OFN',
    nome: 'Ofício (CN) de Relatório Anual da Agência Nacional de Transportes Aquaviários - Antaq',
  },
  {
    cod: '833',
    sigla: '',
    nome: 'L) DOCUMENTOS DE CPI',
  },
  {
    cod: '834',
    sigla: 'DOCCPI',
    nome: 'Documento de CPI',
  },
  {
    cod: '835',
    sigla: 'DOCCPI',
    nome: 'Documento de CPI sigiloso',
  },
  {
    cod: '836',
    sigla: 'OFJ',
    nome: 'Ofício de Órgão do Poder Judiciário',
  },
  {
    cod: '837',
    sigla: 'OFE',
    nome: 'Ofício de Órgão do Poder Executivo',
  },
  {
    cod: '838',
    sigla: 'MAD',
    nome: 'Manifestação do(a) Denunciado(a)',
  },
  {
    cod: '839',
    sigla: 'PDC',
    nome: 'Projeto de Decreto Legislativo sobre Declaração de Guerra e correlatos',
  },
  {
    cod: '840',
    sigla: 'PDC',
    nome: 'Projeto de Decreto Legislativo sobre Estado de Defesa, Estado de Sítio e Intervenção Federal nos Estados',
  },
  {
    cod: '841',
    sigla: 'PDC',
    nome: 'Projeto de Decreto Legislativo sobre transferência temporária da sede do Governo Federal',
  },
  {
    cod: '842',
    sigla: 'PDC',
    nome: 'Projeto de Decreto Legislativo para autorizar o Presidente ou o Vice-Presidente da República a se ausentarem do paíse, por mais de 15 dias (art. 49, II, CF)',
  },
  {
    cod: '843',
    sigla: 'SIP',
    nome: 'Solicitação para instauração de processo',
    descricao: 'Artigo 217 do RICD',
  },
  {
    cod: '844',
    sigla: 'REC',
    nome: 'Recurso contra aplicação de censura escrita (Art. 12, § 2º do CEDP)',
    descricao: 'Contra aplicação de censura escrita (Art. 12, § 2º do CEDP)',
  },
  {
    cod: '845',
    sigla: 'OF',
    nome: 'Demonstrativo de emissão do real',
  },
  {
    cod: '846',
    sigla: 'DTQ',
    nome: 'Destaque para Votação em Separado',
  },
  {
    cod: '847',
    sigla: 'DTQ',
    nome: 'Destaque de Bancada',
  },
  {
    cod: '848',
    sigla: 'RCEX',
    nome: 'Relatório de Comissão Externa',
  },
  {
    cod: '849',
    sigla: 'RCEL',
    nome: 'Relatório de Comissão de Estudo Legislativo',
  },
  {
    cod: '850',
    sigla: 'DEF',
    nome: 'Defesa Escrita',
  },
  {
    cod: '851',
    sigla: 'DEF',
    nome: 'Defesa Prévia',
  },
  {
    cod: '852',
    sigla: 'PRLP',
    nome: 'Parecer Preliminar',
  },
  {
    cod: '853',
    sigla: 'PRLP(V)',
    nome: 'Parecer Preliminar Vencedor',
  },
  {
    cod: '854',
    sigla: 'RGT',
    nome: 'Relatório de Grupo de Trabalho',
  },
  {
    cod: '855',
    sigla: 'REL-A',
    nome: 'Relatório Adotado pela Comissão',
  },
  {
    cod: '856',
    sigla: 'RRR',
    nome: 'Relatório Reformulado',
  },
  {
    cod: '857',
    sigla: 'RVC',
    nome: 'Relatório Vencedor',
  },
  {
    cod: '858',
    sigla: 'CMC',
    nome: 'Comunicação de Medida Cautelar',
  },
  {
    cod: '859',
    sigla: 'DOC',
    nome: 'Indicação de Líder de Partido ou Bloco Parlamentar',
  },
  {
    cod: '860',
    sigla: 'DOC',
    nome: 'Indicação de Vice-Líder de Partido ou Bloco Parlamentar',
  },
  {
    cod: '861',
    sigla: 'DOC',
    nome: 'Adesão a Grupo Parlamentar Registrado',
  },
  {
    cod: '862',
    sigla: 'DOC',
    nome: 'Desligamento de Grupo Parlamentar Registrado',
  },
  {
    cod: '863',
    sigla: 'DOC',
    nome: 'Constituição de Bloco Parlamentar',
  },
  {
    cod: '864',
    sigla: 'DOC',
    nome: 'Adesão a Bloco Parlamentar',
  },
  {
    cod: '865',
    sigla: 'DOC',
    nome: 'Desligamento de Bloco Parlamentar',
  },
  {
    cod: '866',
    sigla: 'DOC',
    nome: 'Indicação de Coordenador de Bancada Estadual',
  },
  {
    cod: '867',
    sigla: 'REQ',
    nome: 'Requerimento de Inclusão na Ordem do Dia (Res 14/20, art. 4º, §3º)',
  },
  {
    cod: '868',
    sigla: 'MIP',
    nome: 'Minuta de Proposição Legislativa',
  },
  {
    cod: '869',
    sigla: 'EMC',
    nome: 'Emenda à PEC',
  },
  {
    cod: '870',
    sigla: 'EMP',
    nome: 'Emenda de Plenário a Projeto com Urgência ',
  },
  {
    cod: '871',
    sigla: 'EMP',
    nome: 'Emenda de Plenário a Projeto em Fase de Discussão do 2º Turno ',
  },
  {
    cod: '872',
    sigla: 'ERD',
    nome: 'Emenda de Redação em Plenário',
  },
  {
    cod: '873',
    sigla: 'EMP',
    nome: 'Emenda de Plenário à MPV (Ato Conjunto 1/20)',
  },
  {
    cod: '874',
    sigla: 'RPD',
    nome: 'Requerimento de Discussão por Partes',
  },
  {
    cod: '875',
    sigla: 'RPD',
    nome: 'Requerimento de quebra de insterstício para verificação de votação',
  },
  {
    cod: '876',
    sigla: 'RPD',
    nome: 'Requerimento de Inversão de Pauta',
  },
  {
    cod: '877',
    sigla: 'RPD',
    nome: 'Requerimento de Encerramento da Discussão de Projeto de Código',
  },
  {
    cod: '878',
    sigla: 'REQ',
    nome: 'Requerimento de Urgência (art. 154, I ou III, do RICD)',
  },
  {
    cod: '887',
    sigla: 'ECN',
    nome: 'Emenda (CN)',
    descricao: 'Emenda a Projeto do Congresso Nacional',
  },
  {
    cod: '888',
    sigla: 'DTS',
    nome: 'Destaque Simples',
  },
  {
    cod: '889',
    sigla: 'RPD',
    nome: 'Requerimento Procedimental Genérico de Sessão/Reunião',
  },
  {
    cod: '890',
    sigla: 'RPD',
    nome: 'Requerimento de Retirada de Tramitação de Proposição em Sessão ou Reunião',
  },
  {
    cod: '891',
    sigla: 'PRLP',
    nome: 'Parecer Preliminar de Plenário',
  },
  {
    cod: '892',
    sigla: 'RPD',
    nome: 'Requerimento de Adiamento da Discussão de Matéria Urgente',
  },
  {
    cod: '895',
    sigla: 'AJECN',
    nome: 'Ajuste de Emenda Orçamentária (CN)',
    descricao: 'Ajuste de Emenda Orçamentária do Congresso Nacional',
  },
  {
    cod: '896',
    sigla: 'SRL',
    nome: 'Sugestão a Relatório (CN)',
    descricao: 'Sugestão a Relatório do Congresso Nacional',
  },
  {
    cod: '897',
    sigla: 'ATACN',
    nome: 'Ata (CN)',
    descricao: 'Ata do Congresso Nacional',
  },
  {
    cod: '898',
    sigla: 'REQ',
    nome: 'Requerimento de Tramitação de Tratado Internacional nos Termos do art. 5º, § 3º, da CF',
    descricao:
      'Requerimento - Tramitação de tratado internacional nos termos do art. 5º, § 3º, da CF',
  },
  {
    cod: '899',
    sigla: 'RPD',
    nome: 'Requerimento Procedimental de Retirada de Assinatura de RPD e DTQ',
    descricao: 'Requerimento Procedimental de Retirada de Assinatura',
  },
  {
    cod: '1000',
    sigla: 'RPD',
    nome: 'Requerimento de Encerramento da Discussão e do Encaminhamento de Matéria Urgente',
  },
  {
    cod: '1001',
    sigla: 'PRLE',
    nome: 'Parecer Preliminar às Emendas de Plenário',
  },
  {
    cod: '1002',
    sigla: 'DOC',
    nome: 'Denominação de Bloco Parlamentar',
  },
  {
    cod: '1003',
    sigla: 'DOC',
    nome: 'Ofício da Primeira-Secretaria',
  },
  {
    cod: '1004',
    sigla: 'PRO',
    nome: 'Proposta de Plano para Comissão',
  },
  {
    cod: '1005',
    sigla: 'PRO',
    nome: 'Proposta de Regulamento',
  },
  {
    cod: '1006',
    sigla: 'RLG',
    nome: 'Relatório Geral',
  },
  {
    cod: '1007',
    sigla: 'QO',
    nome: 'Questão de Ordem',
  },
  {
    cod: '1008',
    sigla: 'APM',
    nome: 'Complemento de Apoiamento',
  },
  {
    cod: '1009',
    sigla: 'CFIS',
    nome: 'Relatório de Atividades do Comitê de Avaliação, Fiscalização e Controle de Execução Orçamentária',
  },
  {
    cod: '1010',
    sigla: 'RPDR',
    nome: 'Requerimento de Alteração da Ordem dos Trabalhos',
  },
  {
    cod: '1011',
    sigla: 'DTQ',
    nome: 'Destaque de Emenda',
  },
  {
    cod: '1012',
    sigla: 'DTQ',
    nome: 'Destaque de Preferência',
  },
  {
    cod: '1013',
    sigla: 'DTQ',
    nome: 'Destaque para Proposição Autônoma',
  },
  {
    cod: '1015',
    sigla: 'REQ',
    nome: 'Requerimento para envio de Solicitação de Informação ao TCU pela Comissão',
  },
  {
    cod: '1016',
    sigla: 'REQ',
    nome: 'Requerimento para envio de Indicação pela Comissão',
  },
  {
    cod: '1017',
    sigla: 'REQ',
    nome: 'Requerimento para envio de Requerimento de Informação pela Comissão',
  },
  {
    cod: '1018',
    sigla: 'REQ',
    nome: 'Requerimento de Convocação em CPI (art. 58, §3º, CF)',
  },
  {
    cod: '1019',
    sigla: 'RPD',
    nome: 'Requerimento de Inclusão de Matéria na Ordem do Dia para Apreciação Imediata',
  },
  {
    cod: '1020',
    sigla: 'DEF',
    nome: 'Defesa',
  },
  {
    cod: '1021',
    sigla: 'DEF',
    nome: 'Complementação de Defesa',
  },
  {
    cod: '1022',
    sigla: 'DEF',
    nome: 'Alegações Finais',
  },
  {
    cod: '1023',
    sigla: 'DEF',
    nome: 'Memoriais',
  },
  {
    cod: '1024',
    sigla: 'DOC',
    nome: 'Indicação ou Desligamento de Membros de Comissão',
  },
  {
    cod: '1025',
    sigla: 'INC',
    nome: 'Indicação à Mesa',
  },
  {
    cod: '1026',
    sigla: 'DOC',
    nome: 'Instalação de Grupo Parlamentar',
  },
  {
    cod: '1027',
    sigla: 'DOC',
    nome: 'Ato da Presidência da Comissão',
  },
  {
    cod: '1028',
    sigla: 'DOC',
    nome: 'Ofício do Senado Federal',
  },
  {
    cod: '1029',
    sigla: 'REQ',
    nome: 'Requerimento de Requisição de Informação e Documentação em CPI (art. 58, §3º, CF)',
  },
  {
    cod: '1030',
    sigla: 'REQ',
    nome: 'Requerimento de Quebra de Sigilo em CPI (art. 58, §3º, CF)',
  },
  {
    cod: '1031',
    sigla: 'REQ',
    nome: 'Requerimento de Busca e Apreensão em CPI (art. 58, §3º, CF)',
  },
  {
    cod: '1032',
    sigla: 'REQ',
    nome: 'Requerimento de Realização de Diligências em CPI (art. 58, §3º, CF)',
  },
  {
    cod: '1033',
    sigla: 'DOC',
    nome: 'Ofício do Congresso Nacional',
  },
  {
    cod: '1034',
    sigla: 'PPR',
    nome: 'Parecer Reformulado de Plenário às Emendas de Plenário',
  },
  {
    cod: '1035',
    sigla: 'DOC',
    nome: 'Adesão a Frente Parlamentar Registrada',
  },
  {
    cod: '1036',
    sigla: 'DOC',
    nome: 'Desligamento de Frente Parlamentar Registrada',
  },
  {
    cod: '1037',
    sigla: 'REQ',
    nome: 'Requerimento para envio de ofício solicitando informações',
  },
  {
    cod: '1038',
    sigla: 'RPD',
    nome: 'Votação Nominal do Requerimento de Adiamento da Discussão',
  },
  {
    cod: '1039',
    sigla: 'RPD',
    nome: 'Votação Nominal do Requerimento de Adiamento da Discussão (matéria urgente)',
  },
  {
    cod: '1040',
    sigla: 'RPD',
    nome: 'Votação Nominal do Requerimento de Adiamento da Votação',
  },
  {
    cod: '1041',
    sigla: 'RPD',
    nome: 'Votação Nominal do Requerimento de Adiamento da Votação (matéria urgente)',
  },
  {
    cod: '1042',
    sigla: 'RPD',
    nome: 'Votação Nominal do Requerimento de Alteração da Ordem dos Trabalhos',
  },
  {
    cod: '1043',
    sigla: 'RPD',
    nome: 'Votação Nominal do Requerimento de Encerramento da Discussão (Comissões)',
  },
  {
    cod: '1044',
    sigla: 'RPD',
    nome: 'Votação Nominal do Requerimento de Encerramento da Discussão (Plenário)',
  },
  {
    cod: '1045',
    sigla: 'RPD',
    nome: 'Votação Nominal do Requerimento de Encerramento da Discussão e do Encaminhamento da Votação',
  },
  {
    cod: '1046',
    sigla: 'RPD',
    nome: 'Votação Nominal do Requerimento de Inclusão de Matéria para Apreciação Imediata',
  },
  {
    cod: '1047',
    sigla: 'RPD',
    nome: 'Votação Nominal do Requerimento de Inversão da Pauta',
  },
  {
    cod: '1048',
    sigla: 'RPD',
    nome: 'Votação Nominal do Requerimento de Preferência',
  },
  {
    cod: '1049',
    sigla: 'RPD',
    nome: 'Votação Nominal do Requerimento de Retirada de Matéria da Ordem do Dia',
  },
  {
    cod: '1050',
    sigla: 'RPD',
    nome: 'Votação Nominal do Requerimento de Retirada de Tramitação de RPD e DTQ',
  },
  {
    cod: '1051',
    sigla: 'RPD',
    nome: 'Votação Nominal do Destaque para Votação em Separado',
  },
  {
    cod: '1052',
    sigla: 'RPD',
    nome: 'Votação Nominal do Requerimento de Emenda',
  },
  {
    cod: '1053',
    sigla: 'RPD',
    nome: 'Votação Nominal do Destaque de Emenda',
  },
  {
    cod: '1054',
    sigla: 'RPD',
    nome: 'Votação Nominal do Destaque para Proposição Autônoma',
  },
  {
    cod: '1055',
    sigla: 'RPD',
    nome: 'Votação Nominal do Destaque de Preferência',
  },
  {
    cod: '1056',
    sigla: 'RPD',
    nome: 'Votação Nominal do Requerimento Procedimental Genérico',
  },
  {
    cod: '1057',
    sigla: 'RPD',
    nome: 'Votação Nominal do Requerimento de Retirada de Assinatura de RPD e DTQ',
  },
  {
    cod: '1058',
    sigla: 'TVR',
    nome: 'Renovação Rádio Ondas Médias adaptada para Frequência Modulada',
  },
  {
    cod: '1059',
    sigla: 'TVR',
    nome: 'Renovação Rádio Ondas Médias Educativa adaptada para Frequência Modulada Educativa',
  },
]
